### ISSUE TITLE
Autocomplete input in surveys

### ISSUE THREAD

**Issue by Lintu00** [OnePointGlobal/OnePoint-Global-Feedback-Toolkit#4]
Is there a way for us to add autocomplete validation using OneScript?
We would like to add an autocomplete field and have trouble finding some documentation related to this.

**Comment by dougmorris** [comment]
@Lintu00 to confirm this has been picked up via an email conversation. Autocomplete is available through a combination of OneScript, HTML, CSS and JavaScript. Can you be more specific with the requirement so we can provide an example as the requirement so far defined is very broad.

**Comment by Lintu00** [comment]
Hi @dougmorris 

What we want specifically is to add an input field on one of the survey pages and when a user types he will be required to choose an option from a list of matched hospital names.
What I am curious about is how this can be done using OneScript, since we need to save whatever value is selected on the same variable we are using now.
We are currently selecting that variable from a radio button list but that list has since grown to have around 240 options, so scrolling through the list became troublesome.
This is an example of how we are building the list now:
`question_10 "At which hospital do you receive the main treatment?"
 categorical [1..1]
    {
        R1 "Hospital1",
        R2 "Hospital2",
         ...
        R100 "Hospital100"
    };
`
There wouldn't be a problem implementing the autocomplete with regular html/javascript, but i'm having trouble figuring out how to add it through OneScript code. The autocomplete answer would still need to be saved as "question_10" in order to keep the data consistent with what we have now.

**Comment by dougmorris** [comment]
PLease see the attached example. It relies on understanding the use of a question.xsl stylesheet that allows you to change the generated HTML. This example also relies on jQuery Mobile to implement an auto complete feature. This can be modified to achieve what you are looking for. Please do not hesitate to ask for more information if you require it.

[test 20171118.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1484802/test.20171118.zip)

**Comment by Lintu00** [comment]
Hello @dougmorris,
Thank you for the example, it's exactly what we needed to add.
There is a small issue concerning it though, the fact that after you select a value for the autocomplete and move on to the next page. the value is cleared from the input upon returning, unlike the other inputs that keep your previous answers. 
Also once you select a value for the autocomplete and then delete the text it will still consider the input as valid and let you move on to the next page.
Despite that, we might still use this as it's already a better alternative to scrolling through 250 options, and it's not that likely a user will return to previous questions.
I'll keep trying to find what might cause that input to not keep the value like regular inputs do, but if you have an idea on how to fix this it would help us greatly.

**Comment by dougmorris** [comment]
@Lintu00 Thanks for the feedback - I will take a look for you and see if I can find a solution to filling in the field when you move back. I know what the problem is with  deleting the entry - need to make a modification to the javascript to enhance this. I will post an update as soon as I am able to.

**Comment by dougmorris** [comment]
@Lintu00 This version sorts out the previous button problem, but not sure about the blanking out the text box yet.

[test 20171121.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1491339/test.20171121.zip)

**Comment by Lintu00** [comment]
Hi @dougmorris,
The second version you sent me is missing the Question.xsl file, but I added the one from your previous example and it indeed works, as in, it shows the value that I added when I navigate back from another page. But the rest of code seems identical to the first version, so I'm not sure how it behaves different and what to change in my own project to apply this fix. I can't seem to find the change in the code.

**Comment by dougmorris** [comment]
[test 20171122.zip](https://github.com/OnePointGlobal/OnePoint-Global-Feedback-Toolkit/files/1497008/test.20171122.zip)

Hi @Lintu00,

It does not make sense to me because that's here I made the change. I have supplied the full project again. Perhaps it will look different if you use this version?

**Comment by Lintu00** [comment]
Thank you @dougmorris,
This version works for me.
