### ISSUE TITLE
Date type question problem

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Feedback-Toolkit#6]
When we add a date type question from editor and check the same in the preview, the calendar isn't appearing (it just acts as a text box).

**Comment by dougmorris** [comment]
@brijeshonepoint if you can confirm any issues from the HTML side I will investigate as required.

**Comment by brijeshonepoint** [comment]
> 
> 
> @brijeshonepoint if you can confirm any issues from the HTML side I will investigate as required.

Yes @dougmorris I have checked it in widget file, we are sending input type as date but when it comes to survey it is changing input type as datetime. 

![image](https://user-images.githubusercontent.com/38459171/65138860-481ec080-da29-11e9-89e9-59b9a1af0806.png)

**Comment by dougmorris** [comment]
@brijeshonepoint thanks - I will look into it further.

**Comment by dougmorris** [comment]
I can see the error and will have it fixed in the next release of the XML to OneScript.

**Comment by dougmorris** [comment]
This is available on dev now.

**Comment by pavithra-opg** [comment]
Issue with date question works
