### ISSUE TITLE
Cannot Download OPGS/One file from Toolkit Edit Feature

### ISSUE THREAD

**Issue by James-OPG** [OnePointGlobal/OnePoint-Global-Feedback-Toolkit#7]
Conditions:  Upload an OPGS script to the account toolkit and save it.  

Edit it and click the download opgs or download one file links - nothing happens.  

![image](https://user-images.githubusercontent.com/28926171/66516957-396b7c80-eab0-11e9-9437-18988b0226da.png)

**Comment by dougmorris** [comment]
@James-OPG thanks for this - I cannot replicate this. Please can you share the file you uploaded.

**Comment by James-OPG** [comment]
Github wouldn't allow me to attach it here - I've sent it via email.

**Comment by dougmorris** [comment]
@James-OPG @hitesh-opg I am unable to replicate this. Can you confirm the exact steps to go through please.

**Comment by hitesh-opg** [comment]
@dougmorris , it works in Chrome but in firefox, the files are not getting downloaded.

**Comment by James-OPG** [comment]
Correct @hitesh-opg - thanks for clarifying.  I was testing using firefox.  Might be worth confirming when fixed it works in most major browsers.

**Comment by dougmorris** [comment]
@hitesh-opg @James-OPG are we closing this issue?

**Comment by dougmorris** [comment]
@hitesh-opg @James-OPG I have checked this and it does not work on Firefox. This is therefore UI problem and I am assigning it to @brijeshonepoint and @shobhitOne

**Comment by onepointpb** [comment]
Just tested this on Firefox. I am able to download both .one and .opgs files on Live.
