### ISSUE TITLE
Cannot edit profile elements once set manually

### ISSUE THREAD

**Issue by James-OPG** [OnePointGlobal/OnePoint-Global-Feedback-Toolkit#8]
Condition - create a new panel and panelists.  Add a profile element manually.  Edit that profile element - it throws an error.

![image](https://user-images.githubusercontent.com/28926171/66517313-e940ea00-eab0-11e9-971b-2a314c35d29a.png)

**Comment by dougmorris** [comment]
@James-OPG @hitesh-opg I am unable to replicate the problem. I need an exact process to copy to get it go wrong.

**Comment by hitesh-opg** [comment]
@dougmorris I am not able to replicate it myself. The edit worked for me. Would need @James-OPG to confirm the steps he took.

**Comment by James-OPG** [comment]
Not sure what was fixed in the meantime, but it seems to have resolved this issue.  I cannot replicate it anymore, and the original panel that was throwing the error will now allow me to edit the elements successfully.
