### ISSUE TITLE
Question Editor MaxDiff Preview "undefined" option labels displayed in Firefox

### ISSUE THREAD

**Issue by dougmorris** [OnePointGlobal/OnePoint-Global-Feedback-Toolkit#9]
For a MaxDiff Question in Preview on Firefox the Question does not display the correct labels for the options. However they do not look correct in Chrome.

Chrome
![image](https://user-images.githubusercontent.com/4094389/66737958-38966a00-ee65-11e9-9b04-09327eb42f34.png)

Firefox
![image](https://user-images.githubusercontent.com/4094389/66737983-506dee00-ee65-11e9-8d25-18ed7830db4d.png)

Field is defined in OneScript as:
```
Q9 - loop[1..5] 
    fields ( _set "This is a Max Diff Question<maxdiff/><min>Least</min><max>Most</max>"
        style(control(type="MaxDiff")) loop {
                a "Option A"    factor(1),
        b "Option B"    factor(2),
        c "Option C"    factor(3),
        d "Option D"    factor(4),
        e "Option E"    factor(5),
        f "Option F"    factor(6),
        g "Option G"    factor(7),
        h "Option H"    factor(8),
        i "Option I"    factor(9)

        } fields - ( importance integer [0..2];
        );
```

and the Routing Script is:
```
br_Q9:
    var Q9__full = {a,b,c,d,e,f,g,h,i};
    for each questionset in Q9 {
        if (questionset._set.QuestionFilter = Q9__full) {
            questionset._set.QuestionFilter = Ran(Q9__full, 3);
        }

        questionset.ask();
    }
```

**Comment by dougmorris** [comment]
@brijeshonepoint @shobhitOne has been resolved?

**Comment by brijeshonepoint** [comment]
@dougmorris Yes It was fixed, might be not updated or multiple creation of the issue.
